name: flash_chat
description: A new Flutter application.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  animated_text_kit: ^1.3.0
  firebase_core: ^0.3.4 #^1.0.4
  firebase_auth: ^0.8.4+4 #^1.1.1
  cloud_firestore: ^0.9.13+1 #^1.0.6
  modal_progress_hud: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - images/
